import { GlossaryEntry } from '@/types/content';

/** Plain-language glossary. Every term must be explained without jargon. */
export const GLOSSARY: GlossaryEntry[] = [
  { id: 'g-forex', term: 'Forex', plain: 'The global market where one currency is exchanged for another.', example: 'Swapping euros for dollars is a forex transaction.' },
  { id: 'g-pair', term: 'Currency pair', plain: 'Two currencies quoted together. The first (base) is priced in the second (quote).', example: 'EUR/USD = 1.10 means one euro costs 1.10 dollars.' },
  { id: 'g-base', term: 'Base currency', plain: 'The first currency in a pair — the thing being priced.' },
  { id: 'g-quote', term: 'Quote currency', plain: 'The second currency in a pair — the money the price is stated in.' },
  { id: 'g-pip', term: 'Pip', plain: 'The standard unit of price movement: 0.0001 for most pairs, 0.01 for JPY pairs.', example: 'EUR/USD from 1.1000 to 1.1005 moved 5 pips.' },
  { id: 'g-pipette', term: 'Pipette', plain: 'One tenth of a pip — the 5th decimal on most pairs.' },
  { id: 'g-bid', term: 'Bid', plain: 'The price buyers are offering — the price YOU get when selling.' },
  { id: 'g-ask', term: 'Ask', plain: 'The price sellers demand — the price YOU pay when buying.' },
  { id: 'g-spread', term: 'Spread', plain: 'The gap between bid and ask — the built-in cost of every trade.' },
  { id: 'g-lot', term: 'Lot', plain: 'A position-size unit. Standard lot = 100,000 units of the base currency; mini = 10,000; micro = 1,000.' },
  { id: 'g-leverage', term: 'Leverage', plain: 'Controlling a large position with a small deposit. It magnifies both profits and losses.' },
  { id: 'g-margin', term: 'Margin', plain: 'The deposit locked by the broker while a leveraged position is open.' },
  { id: 'g-long', term: 'Long', plain: 'A trade that profits if price rises: buy first, sell later.' },
  { id: 'g-short', term: 'Short', plain: 'A trade that profits if price falls: sell first, buy back later.' },
  { id: 'g-ohlc', term: 'OHLC', plain: 'The four prices of a candle: Open, High, Low, Close.' },
  { id: 'g-candle-body', term: 'Candle body', plain: 'The thick part of a candle, from open to close.' },
  { id: 'g-wick', term: 'Wick', plain: 'The thin line beyond a candle body — price territory that was explored but rejected.' },
  { id: 'g-timeframe', term: 'Timeframe', plain: 'How much time one candle covers, e.g. M15 = 15 minutes, H4 = 4 hours, D1 = 1 day.' },
  { id: 'g-swing-high', term: 'Swing high', plain: 'A local peak: a candle with lower highs on both sides.' },
  { id: 'g-swing-low', term: 'Swing low', plain: 'A local valley: a candle with higher lows on both sides.' },
  { id: 'g-uptrend', term: 'Uptrend', plain: 'A sequence of higher highs and higher lows.' },
  { id: 'g-downtrend', term: 'Downtrend', plain: 'A sequence of lower lows and lower highs.' },
  { id: 'g-range', term: 'Range', plain: 'Sideways movement between a ceiling and a floor, with no lasting direction.' },
  { id: 'g-pullback', term: 'Pullback', plain: 'A temporary move against the trend before it continues.' },
  { id: 'g-impulse', term: 'Impulse', plain: 'A strong, directional price move — the engine of a trend.' },
  { id: 'g-bos', term: 'Break of structure', plain: 'When price breaks the swing pattern, e.g. an uptrend making a lower low.' },
  { id: 'g-support', term: 'Support', plain: 'An area below price where falls have previously stopped.' },
  { id: 'g-resistance', term: 'Resistance', plain: 'An area above price where rallies have previously stalled.' },
  { id: 'g-role-reversal', term: 'Role reversal', plain: 'Broken resistance acting as support afterwards (or the opposite).' },
  { id: 'g-retest', term: 'Retest', plain: 'Price returning to a broken level to "test" it before continuing.' },
  { id: 'g-breakout', term: 'Breakout', plain: 'Price escaping a range or level with follow-through.' },
  { id: 'g-fakeout', term: 'Fakeout', plain: 'A breakout that fails: price pokes beyond a level, then snaps back.' },
  { id: 'g-confluence', term: 'Confluence', plain: 'Several independent reasons pointing to the same trade area.' },
  { id: 'g-market-order', term: 'Market order', plain: 'An order that executes immediately at the current price.' },
  { id: 'g-limit-order', term: 'Limit order', plain: 'An order waiting to fill at a better price than now.' },
  { id: 'g-stop-order', term: 'Stop order', plain: 'An order that triggers at a worse price than now — for breakouts or protective exits.' },
  { id: 'g-stop-loss', term: 'Stop-loss', plain: 'The pre-placed order that closes a losing trade at your maximum accepted loss.' },
  { id: 'g-take-profit', term: 'Take-profit', plain: 'The pre-placed order that closes a winning trade at your target.' },
  { id: 'g-slippage', term: 'Slippage', plain: 'The difference between the price you expected and the price you actually got.' },
  { id: 'g-swap', term: 'Swap / rollover', plain: 'A small credit or charge for holding a position overnight, based on interest-rate differences.' },
  { id: 'g-rr', term: 'Reward-to-risk ratio', plain: 'Planned reward divided by planned risk. Risk 20 pips to target 40 = 1:2.' },
  { id: 'g-r-multiple', term: 'R-multiple', plain: 'A result measured in units of initial risk. Losing your full stop = −1R; winning twice your risk = +2R.' },
  { id: 'g-position-sizing', term: 'Position sizing', plain: 'Calculating trade size so a stop-out loses exactly your planned amount.' },
  { id: 'g-drawdown', term: 'Drawdown', plain: 'The drop from your account’s peak to its lowest point after it.' },
  { id: 'g-expectancy', term: 'Expectancy', plain: 'The average R you earn per trade over many trades: (win% × avg win) − (loss% × avg loss).' },
  { id: 'g-profit-factor', term: 'Profit factor', plain: 'Total winnings divided by total losses. Above 1 means gross profit.' },
  { id: 'g-win-rate', term: 'Win rate', plain: 'The share of trades that win. Meaningless without knowing the size of wins versus losses.' },
  { id: 'g-risk-of-ruin', term: 'Risk of ruin', plain: 'The probability of losing so much that you must stop trading.' },
  { id: 'g-backtesting', term: 'Backtesting', plain: 'Replaying history candle by candle and applying your rules without seeing the future.' },
  { id: 'g-forward-testing', term: 'Forward testing', plain: 'Testing rules in real time (demo or simulation) after a successful backtest.' },
  { id: 'g-look-ahead', term: 'Look-ahead bias', plain: 'Accidentally using future information to make a "historical" decision. It fakes results.' },
  { id: 'g-overfitting', term: 'Overfitting', plain: 'Tuning rules until they perfectly match past data — and only past data.' },
  { id: 'g-cherry-picking', term: 'Cherry-picking', plain: 'Quietly skipping losing setups in a test, which inflates results.' },
  { id: 'g-out-of-sample', term: 'Out-of-sample data', plain: 'Data your rules have never seen, used for final validation.' },
  { id: 'g-fomo', term: 'FOMO', plain: 'Fear of missing out — the urge to chase a move that already happened.' },
  { id: 'g-revenge', term: 'Revenge trading', plain: 'Trading aggressively to "win back" a loss. A leading account killer.' },
  { id: 'g-liquidity', term: 'Liquidity', plain: 'How much buying/selling interest exists. High liquidity = tight spreads and smooth fills.' },
  { id: 'g-session', term: 'Trading session', plain: 'The hours when a financial centre is active: Sydney, Tokyo, London, New York.' },
  { id: 'g-demo', term: 'Demo account', plain: 'A practice account with virtual money and real prices.' },
  { id: 'g-equity-curve', term: 'Equity curve', plain: 'A chart of your account value (or cumulative R) trade after trade.' },
  { id: 'g-sma', term: 'Simple moving average (SMA)', plain: 'The average of the last N closing prices, recalculated every candle. It describes the past and always lags.' },
  { id: 'g-ema', term: 'Exponential moving average (EMA)', plain: 'A moving average that weighs recent prices more heavily, so it turns faster but whipsaws more.' },
  { id: 'g-rsi', term: 'RSI', plain: 'An oscillator (0–100) comparing recent up-closes to down-closes. High readings mean fast recent buying — not that price must fall.' },
  { id: 'g-atr', term: 'ATR', plain: 'Average True Range: the typical size of recent candles. Used to set stops beyond normal market noise.' },
  { id: 'g-overbought', term: 'Overbought / oversold', plain: 'Labels for fast recent buying or selling. They describe speed, not a ceiling or floor — trends can stay "overbought" for weeks.' },
  { id: 'g-hawkish', term: 'Hawkish / dovish', plain: 'Central-bank language leaning toward higher rates (hawkish) or lower rates (dovish).' },
  { id: 'g-priced-in', term: 'Priced in', plain: 'Already reflected in the current price before an event happens. Markets move on surprises, not on what everyone expected.' },
  { id: 'g-calendar', term: 'Economic calendar', plain: 'The schedule of data releases with previous, forecast and actual values, plus an expected impact rating.' },
  { id: 'g-correlation', term: 'Correlation', plain: 'How closely two pairs move together. Two correlated trades can secretly be one doubled bet.' },
  { id: 'g-regime', term: 'Market regime', plain: 'The prevailing character of a market (trending, ranging, calm, volatile). Most strategies only work in their home regime.' },
  { id: 'g-fvg', term: 'Fair value gap', plain: 'A price pocket left by a fast one-directional candle where little two-way trading happened. A descriptive lens — its predictive claims must be tested.' },
  { id: 'g-sweep', term: 'Liquidity sweep', plain: 'Price briefly pushing past an obvious high or low, triggering the stops resting there, then reversing. Another name for a fakeout, seen through orders.' },
  { id: 'g-kyc', term: 'KYC check', plain: 'The standard identity verification regulated brokers must run when you open an account.' },
  { id: 'g-nbp', term: 'Negative balance protection', plain: 'A safeguard ensuring your account cannot go below zero, no matter how fast the market moves.' },
  { id: 'g-double-top', term: 'Double top / bottom', plain: 'Two failed attempts at the same high (or low). Confirmed only when the level between the attempts — the neckline — breaks.' },
  { id: 'g-hns', term: 'Head and shoulders', plain: 'A final higher high (head) between two lower peaks (shoulders) that fails — a classic trend-exhaustion story.' },
  { id: 'g-neckline', term: 'Neckline', plain: 'The confirmation level of a reversal pattern. Until it breaks, the pattern is only a possibility.' },
  { id: 'g-flag', term: 'Flag / pennant', plain: 'A tight, shallow pullback after a strong impulse, suggesting the move may continue.' },
  { id: 'g-measured-move', term: 'Measured move', plain: 'A target estimated by projecting a pattern’s height from its breakout point. An estimate — real levels still outrank it.' },
];
